name: Github actions Maven build

on:
	push:
		branches: [ master ]
jobs:
	build:
		runs-on:	ubuntu-latest
		steps:
			- name: Step 1: checkout main branch from Github
			  uses: actions/checkout@v4
			  
			- name: Step 2: Set up JDK 11
			  uses: actions/setup-java@v4
			  with:
				java-version: '11'
				
			- name: Step 3: Run test
			  run: mvn clean verify -Dcucumber.filter.tags=@Tiki -Dbrowser=chrome -DexecutingEnv=test -DtestedEnv=uat -Dplatform=desktop
			  
			- name: Step 4: Creating staging folder
			  run: mkdir staging && cp target/*.jar staging
			  
			- name: Step 5: Uploading staging
			  uses: actions/upload-artifact@v4
			  with:
				name: Package
				path: staging
